#!/usr/bin/env python3

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_cancel_checkpoints_fixture import (
    enclosing,
    function_spans,
    preprocessor_mask,
    strip_noise,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
TPM2_DIR = REPO_ROOT / "libtpms" / "src" / "tpm2"
FIXTURE = REPO_ROOT / "src" / "library" / "tpm2" / "testdata" / "failure_locations.txt"

FUNCTIONS = {
    "ExecuteCommand",
    "NvPowerOn",
    "TestHash",
    "TestSymmetricAlgorithm",
    "TestECDH",
    "TestRsaEncryptDecrypt",
    "DRBG_Generate",
    "EncryptDRBG",
    "BnDiv",
}

SITE = re.compile(
    r"\b(SELF_TEST_FAILURE|FAIL_IMMEDIATE|FAIL_BOOL|FAIL_RC|FAIL_VOID|FAIL|TpmLogFailure)\s*[(;]?"
)


def build_fixture() -> str:
    records: list[tuple[str, int, str, str]] = []
    for path in sorted(TPM2_DIR.rglob("*.c")):
        text = path.read_text(errors="replace")
        if not any(name in text for name in FUNCTIONS):
            continue
        clean = strip_noise(text)
        spans = function_spans(clean)
        mask = preprocessor_mask(clean)
        relative = path.relative_to(REPO_ROOT).as_posix()
        for number, line in enumerate(clean, start=1):
            if mask[number - 1]:
                continue
            match = SITE.search(line)
            if match is None:
                continue
            function = enclosing(spans, number)
            if function not in FUNCTIONS:
                continue
            form = " ".join(line.strip().rstrip(";").split())
            records.append((relative, number, function, form))

    records.sort()
    header = [
        "# Generated by scripts/generate_failure_locations_fixture.py -- do not edit.",
        "# Every FAIL-family and TpmLogFailure site inside the vendored functions",
        "# the Rust FailureLocation mapping mirrors (FAIL_TRACE records the",
        "# function's first four __func__ bytes, the site line and the",
        "# fatal-error code).",
        "# file\tline\tfunction\tform",
    ]
    body = [f"{path}\t{line}\t{function}\t{form}" for path, line, function, form in records]
    return "\n".join(header + body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in fixture instead of rewriting it",
    )
    args = parser.parse_args()

    fixture = build_fixture()

    if args.check:
        current = FIXTURE.read_text() if FIXTURE.is_file() else None
        if current != fixture:
            print(
                f"error: {FIXTURE} is stale; rerun {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        entries = sum(1 for line in fixture.splitlines() if not line.startswith("#"))
        print(f"{FIXTURE}: OK ({entries} entries)")
        return 0

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(fixture)
    entries = sum(1 for line in fixture.splitlines() if not line.startswith("#"))
    print(f"wrote {FIXTURE} ({entries} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
